@startuml
package services {
    interface IReport<T> {
        + GenerateReport(T entity, int offset, int limit): Task<string>
    }
    IReport <|.. BorrowStatusReport
    IReport <|.. PatronBorrowReport

    interface ISearchStrategy<T, I> {
        + SearchByPage(I criteria, int pageNumber, int pageSize): Task<List<T>>
    }
}
@enduml

