@startuml
'skinparam wrapWidth 200
skinparam linetype polyline
title Library System - Class diagram

' domain
!include domain/entity.puml
!include domain/repository.puml
!include domain/services.puml
!include domain/validator.puml

' infraestructure
!include infraestructure/services.puml
!include infraestructure/repository.puml


' presentation
!include presentation/presentation.puml

package logger {
    class ErrorLogger {
       + {static} LogErrorBasedOnSeverity(SeverityLevel severity, string message, Exception ex): void
    }
}
@enduml

