@startuml
'skinparam wrapWidth 200
skinparam linetype polyline

title Library System - Class diagram
' presentation
!include presentation.puml

' infraestructure/:
!include infraestructure/services.puml
!include infraestructure/repository.puml

' domain
!include domain/entity.puml
!include domain/repository.puml
!include domain/services.puml

@enduml

